version: '3.4'

services:
  webapi:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
